### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Arunsp2000**

### CODE REVIEW

**Comment by agupta15k** [comment]
@all-contributors please add @jakebolam for infrastructure, tests and code

**Comment by agupta15k** [comment]
@all-contributors please add @nagarajumadamshetti  for infrastructure, tests and code

**Comment by agupta15k** [comment]
@all-contributors please add @agupta15k for infrastructure, tests and code

**Comment by agupta15k** [comment]
https://github.com/all-contributors please add @nitesh31mishra  for infrastructure, tests and code

**Comment by agupta15k** [comment]
https://github.com/all-contributors please add @sumitsinghhazard for infrastructure, tests and code

**Review by agupta15k — COMMENTED** [review]
Approved.

**Review by nagarajumadamshetti — COMMENTED** [review]
Approved.

**Comment by nagarajumadamshetti** [comment]
https://github.com/all-contributors please add @nitesh31mishra  for infrastructure, tests and code

**Review by agupta15k — COMMENTED** [review]
Approved

**Pull request merged**
